package postgrest

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"errors"
	"math"
	"strings"
	"testing"
	"time"
)

// status is a stringer-style int enum, as generated by golang.org/x/tools/cmd/stringer.
type status int

const statusActive status = 1

func (s status) String() string {
	switch s {
	case statusActive:
		return "Active"
	default:
		return "Unknown"
	}
}

// code is a named string with a String method that must not be used.
type code string

func (code) String() string { return "ignored" }

// label is a non-basic Stringer whose text contains a reserved character.
type label struct{ a, b string }

func (l label) String() string { return l.a + "," + l.b }

// textVal is an encoding.TextMarshaler.
type textVal struct{}

func (textVal) MarshalText() ([]byte, error) { return []byte("(t)"), nil }

// textEnum is an int with MarshalText: TextMarshaler wins over the kind.
type textEnum int

func (textEnum) MarshalText() ([]byte, error) { return []byte("named"), nil }

type badText struct{}

func (badText) MarshalText() ([]byte, error) { return nil, errors.New("boom") }

type badValuer struct{}

func (badValuer) Value() (driver.Value, error) { return nil, errors.New("boom") }

// loopValuer returns itself, which must not recurse forever.
type loopValuer struct{}

func (loopValuer) Value() (driver.Value, error) { return loopValuer{}, nil }

func TestFormatValue(t *testing.T) {
	five := 5
	active := statusActive
	ts := time.Date(2024, 1, 2, 3, 4, 5, 600, time.UTC)
	var nilIface any
	var nilStringer *label
	tests := []struct {
		name     string
		in       any
		want     string
		wantNull bool
	}{
		{"nil", nil, "null", true},
		{"nil_pointer", (*int)(nil), "null", true},
		{"nil_interface_pointer", &nilIface, "null", true},
		{"nil_stringer_pointer", nilStringer, "null", true},
		{"pointer", &five, "5", false},
		{"string", "a,b", "a,b", false},
		{"empty_string", "", "", false},
		{"bool", true, "true", false},
		{"int", -42, "-42", false},
		{"int8", int8(-3), "-3", false},
		{"int64_min", int64(math.MinInt64), "-9223372036854775808", false},
		{"uint64_max", uint64(math.MaxUint64), "18446744073709551615", false},
		{"uintptr", uintptr(9), "9", false},
		{"float32", float32(0.1), "0.1", false},
		{"float64", 1.5, "1.5", false},
		{"float64_large", 1e21, "1000000000000000000000", false},
		{"json_number", json.Number("1.50"), "1.50", false},
		{"raw_message", json.RawMessage(`{"a":1}`), `{"a":1}`, false},
		{"bytes", []byte("abc"), "abc", false},
		{"time", ts, "2024-01-02T03:04:05.0000006Z", false},
		{"time_pointer", &ts, "2024-01-02T03:04:05.0000006Z", false},
		{"stringer_int_enum", statusActive, "1", false},
		{"stringer_int_enum_pointer", &active, "1", false},
		{"stringer_named_string", code("abc"), "abc", false},
		{"stringer_struct", label{"a", "b"}, "a,b", false},
		{"stringer_struct_pointer", &label{"x", "y"}, "x,y", false},
		{"text_marshaler", textVal{}, "(t)", false},
		{"text_marshaler_int", textEnum(3), "named", false},
		{"null_string_valid", sql.NullString{String: "x", Valid: true}, "x", false},
		{"null_string_null", sql.NullString{}, "null", true},
		{"null_int64_valid", sql.NullInt64{Int64: 7, Valid: true}, "7", false},
		{"null_int64_null", sql.NullInt64{}, "null", true},
		{"null_bool", sql.NullBool{Bool: true, Valid: true}, "true", false},
		{"null_float64", sql.NullFloat64{Float64: 2.5, Valid: true}, "2.5", false},
		{"null_time", sql.NullTime{Time: ts, Valid: true}, "2024-01-02T03:04:05.0000006Z", false},
		{"null_string_pointer", &sql.NullString{String: "p", Valid: true}, "p", false},
		{"slice", []int{1, 2}, "1,2", false},
		{"slice_with_nil", []any{nil, statusActive}, "null,1", false},
		{"nil_slice", []int(nil), "", false},
		{"array", [2]string{"a", "b"}, "a,b", false},
		{"map", map[string]int{"a": 1}, `{"a":1}`, false},
		{"struct", struct {
			A int `json:"a"`
		}{1}, `{"a":1}`, false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, null, err := formatScalar(tt.in, 0)
			if err != nil {
				t.Fatal(err)
			}
			assertEq(t, "text", got, tt.want)
			assertEq(t, "null", null, tt.wantNull)
			s, err := formatValue(tt.in)
			if err != nil || s != tt.want {
				t.Errorf("formatValue = %q, %v", s, err)
			}
		})
	}
}

func TestFormatValueErrors(t *testing.T) {
	for name, v := range map[string]any{
		"text_marshaler": badText{},
		"valuer":         badValuer{},
		"valuer_loop":    loopValuer{},
		"json":           map[string]any{"c": make(chan int)},
		"slice_element":  []any{badText{}},
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := formatValue(v); err == nil || !strings.HasPrefix(err.Error(), "postgrest: ") {
				t.Errorf("err = %v", err)
			}
		})
	}
}

// upstream: postgrest-js src/PostgrestFilterBuilder.ts eq (value stringification)
func TestFilterValueKindsOnWire(t *testing.T) {
	c, f, _ := newFake(t, jsonReply(200, `[]`))
	_, err := c.From("tasks").Select("*").
		Eq("status", statusActive).
		Eq("owner", sql.NullString{}).
		Eq("n", sql.NullInt64{Int64: 3, Valid: true}).
		Execute(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	q := f.last(t).Query
	assertEq(t, "status", q.Get("status"), "eq.1")
	assertEq(t, "owner", q.Get("owner"), "eq.null")
	assertEq(t, "n", q.Get("n"), "eq.3")
}

// upstream: postgrest-js src/PostgrestFilterBuilder.ts in (PostgrestReservedCharsRegexp)
func TestInQuotingByFormattedText(t *testing.T) {
	c, f, _ := newFake(t, jsonReply(200, `[]`))
	values := []any{label{"a", "b"}, textVal{}, 1.5, nil, "null", "NULL", `"a,b"`, statusActive, sql.NullString{}, label{"a", "b"}}
	if _, err := c.From("t").Select("*").In("x", values).NotIn("y", []any{textVal{}}).Execute(context.Background()); err != nil {
		t.Fatal(err)
	}
	q := f.last(t).Query
	assertEq(t, "in", q.Get("x"), `in.("a,b","(t)",1.5,null,"null","NULL","\"a,b\"",1)`)
	assertEq(t, "not in", q.Get("y"), `not.in.("(t)")`)
}

// upstream: postgrest-js src/PostgrestFilterBuilder.ts contains (array values)
func TestArrayLiteralQuotingByFormattedText(t *testing.T) {
	c, f, _ := newFake(t, jsonReply(200, `[]`))
	if _, err := c.From("t").Select("*").Contains("tags", []any{nil, "null", label{"a", "b"}, 2, sql.NullInt64{}}).Execute(context.Background()); err != nil {
		t.Fatal(err)
	}
	assertEq(t, "cs", f.last(t).Query.Get("tags"), `cs.{null,"null","a,b",2,null}`)
}

func TestIsJSONObjectish(t *testing.T) {
	tests := map[string]bool{
		``:                  false,
		`   `:               false,
		`{}`:                true,
		` {"a":1}`:          true,
		`[]`:                false,
		`[1,"x",null]`:      false,
		`[1,{"a":1}]`:       true,
		`[[1],[[{"a":1}]]]`: true,
		`[[1],[2]]`:         false,
		`[1,`:               false,
		`"{"`:               false,
		`1`:                 false,
		`null`:              false,
	}
	for in, want := range tests {
		assertEq(t, "isJSONObjectish("+in+")", isJSONObjectish(json.RawMessage(in)), want)
	}
}

// upstream: postgrest-js src/PostgrestQueryBuilder.ts insert/upsert/update, src/PostgrestClient.ts rpc (JSON bodies)
func TestRawJSONBodies(t *testing.T) {
	c, f, _ := newFake(t, jsonReply(201, ""))
	ctx := context.Background()

	if _, err := c.From("users").Insert([]byte(`[{"a": 1}, {"b": 2}]`)).Execute(ctx); err != nil {
		t.Fatal(err)
	}
	r := f.last(t)
	assertEq(t, "insert body", r.Body, `[{"a":1},{"b":2}]`)
	assertEq(t, "insert columns", r.Query.Get("columns"), `"a","b"`)

	if _, err := c.From("users").Upsert(json.RawMessage(`{"id":1}`)).Execute(ctx); err != nil {
		t.Fatal(err)
	}
	assertEq(t, "upsert body", f.last(t).Body, `{"id":1}`)

	if _, err := c.From("users").Update([]byte(`{"name":"x"}`)).Eq("id", 1).Execute(ctx); err != nil {
		t.Fatal(err)
	}
	assertEq(t, "update body", f.last(t).Body, `{"name":"x"}`)

	if _, err := c.RPC("fn", []byte(`{"n": 2}`)).Execute(ctx); err != nil {
		t.Fatal(err)
	}
	assertEq(t, "rpc body", f.last(t).Body, `{"n":2}`)

	if _, err := c.RPC("fn", json.RawMessage(`{"n":[1,2]}`), RPCOptions{Get: true}).Execute(ctx); err != nil {
		t.Fatal(err)
	}
	assertEq(t, "rpc get arg", f.last(t).Query.Get("n"), "{1,2}")

	sent := len(f.requests())
	for name, q := range map[string]FilterBuilder{
		"insert_invalid": c.From("users").Insert([]byte("not json")),
		"upsert_empty":   c.From("users").Upsert(json.RawMessage(nil)),
		"update_invalid": c.From("users").Update([]byte(`{"a":`)),
		"rpc_invalid":    c.RPC("fn", []byte("{")),
	} {
		if _, err := q.Execute(ctx); err == nil || !strings.Contains(err.Error(), "not valid JSON") {
			t.Errorf("%s: err = %v", name, err)
		}
	}
	assertEq(t, "requests for invalid bodies", len(f.requests()), sent)
}
